GestaoConsorcio/Controllers/ComunicacaoController.cs
using GestaoConsorcio.Models.Repositorio;
using GestaoConsorcio.Models.Servicos;
using GestaoConsorcio.Models.View;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestaoConsorcio.Controllers
{
    [Authorize]
    public class ComunicacaoController : Controller
    {
        private ComunicacaoBD combd = new ComunicacaoBD();

        // GET: Comunicacao
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EnviarSms(EnviarSmsVM model)
        {
            combd.SalvarLogSms(Int32.Parse(User.Identity.GetUserId()), model);
            SmsService service = new SmsService();
            service.EnviarSmsSenha(model.ListaTelefones, model.Mensagem);
            return View();
        }
    }
}

GestaoConsorcio/Views/Comunicacao/EnviarSms.cshtml
@{
    ViewBag.Title = "EnviarSms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mensagem Enviada</h2>

GestaoConsorcio/Views/Comunicacao/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("EnviarSms", "Comunicacao", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">
                                               Salvar Contrato
                    </h3>
                </div>
            </div>

            <div class="row">
                @Html.ValidationSummary("", new { @class = "text-danger" })
                <div class="col-lg-12">
                    @if (ViewBag.Visivel == "")
                    {
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="alert @ViewBag.TipoAlert">
                                        <strong>@ViewBag.Mensagem</strong>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                    <div class="row">
                        <div class="col-lg-6">

                            <div class="form-group">
                                <div class="form-group has-feedback">
                                    <div class="form-group has-feedback contratos">
                                        <label>
                                            Telefones separados por virgula (Ex.:11992149801,11992149802):
                                        </label>
                                        <input type="text" class="form-control" name="Telefones">
                                        <br />
                                        <label>
                                            Mensagem
                                        </label>
                                        <input type="text" class="form-control" name="Mensagem" maxlength="160">
                                        <br />
                                        <label>
                                            Numero de Atendimento
                                        </label>
                                        <input type="text" class="form-control" name="NumeroAtendimento">
                                    </div>
                                </div>
                                <div>
                                    <button type="submit" class="btn btn-info">Salvar</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="modal fade modalmsg " data-backdrop="static" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">

                        <div class="modal-body modalbodymsg" role="alert" align="center">

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default btnokmodal" onclick="" data-dismiss="modal">OK</button>
                        </div>

                    </div>

                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </div>
}