GestaoConsorcio/Models/View/DetalheSimulacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GestaoConsorcio.Models.View
{
    public class DetalheSimulacao
    {
        public DetalheSimulacao(List<RetornoSimulacaoConsorcio> simulacao, Financiamento financiamento)
        {
            Simulacao = simulacao;
            Financiamento = financiamento;
        }

        public List<RetornoSimulacaoConsorcio> Simulacao { get; set; }

        public Financiamento Financiamento { get; set; }
    }
}

GestaoConsorcio/Models/View/SimulacaoConsorcio.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GestaoConsorcio.Models.View
{
    public class SimulacaoConsorcio
    {

        public int IdSimulacao { get; set; }

        public int IdUsuario { get; set; }

        public string Nome { get; set; }

        [DataType(DataType.Currency)]
        public decimal ValorCarta { get; set; }

        public decimal Parcela { get; set; }

        //public int Contemplacao { get; set; }

        [DataType(DataType.Currency)]
        public decimal LanceProprio { get; set; }

        public DateTime CriadoEm { get; set; }
    }
}

GestaoConsorcio/Controllers/SimulacaoConsorcioController.cs
using AnalisadorPerfilConsorcio;
using GestaoConsorcio.Models.Repositorio;
using GestaoConsorcio.Models.View;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Caching;
using System.Runtime.Caching;
using System.Configuration;
using GestaoConsorcio.Models.Cache;

namespace GestaoConsorcio.Controllers
{
    public class SimulacaoConsorcioController : Controller
    {
        SimulacaoBD db = new SimulacaoBD();

        static MemoryCache cache = new MemoryCache("MelhoresProspostasCache");
        CacheItemPolicy policy = new CacheItemPolicy { SlidingExpiration = new TimeSpan(0, Convert.ToInt32(ConfigurationManager.AppSettings["CacheExpire"]), 0) };

        public ActionResult Index()
        {
            return View("~/Views/SimulacaoConsorcio/BuscarSimulacao.cshtml");
        }

        public ActionResult NovaSimulacao()
        {
            return View("~/Views/SimulacaoConsorcio/NovaSimulacao.cshtml");
        }

        [HttpPost]
        public JsonResult BuscarSimulacao(string nome, decimal? valor)
        {
            return Json(db.ListarSimulacoes(nome, valor));
        }

        public ActionResult SimularConsorcio(string ValorCarta, string Parcela, string Lance, bool? IncluirGrupoFormacao)
        {
            if (IncluirGrupoFormacao == null)
            {
                IncluirGrupoFormacao = false;
            }
            var valorCarta = Convert.ToInt32(ValorCarta.Substring(0, ValorCarta.Length - 2).Replace(".", "").Replace(",", ""));
            var parcela = Convert.ToInt32(Parcela.Substring(0, Parcela.Length - 2).Replace(".", "").Replace(",", ""));
            var lance = Convert.ToInt32(Lance.Substring(0, Lance.Length - 2).Replace(".", "").Replace(",", ""));
            ConstrutorProposta construtor = new ConstrutorProposta();
            var list = cache;
            List<BuscarMelhoresPropostasResult> melhoresPropostas = new List<BuscarMelhoresPropostasResult>();

            if (list != null && list.GetCount() > 0)
            {
                foreach (var item in list)
                {
                    if (Convert.ToInt32(item.Key) == valorCarta)
                    {
                        foreach (BuscarMelhoresPropostasResult itemCache in (List<BuscarMelhoresPropostasResult>)item.Value)
                        {
                            if (itemCache.Parcela <= parcela && Convert.ToInt64(itemCache.Lance.ToString().Replace(".", "").Replace(",", "")) <= lance)
                            {
                                itemCache.Valor = Convert.ToInt32(item.Key);
                                melhoresPropostas.Add(itemCache);
                            }
                        }
                    }
                }
            }
            if (melhoresPropostas.Count <= 0)
            {
                melhoresPropostas = construtor.BuscarMelhoresPropostas(valorCarta, parcela, lance, 5, 150, (bool)IncluirGrupoFormacao);
            }

            var hs = valorCarta.GetHashCode();

            cache.Add(hs.ToString(), melhoresPropostas, policy);

            ViewBag.ParametrosValorCarta = ValorCarta;
            ViewBag.ParametrosParcela = Parcela;
            ViewBag.ParametrosLance = Lance;

            return View("~/Views/SimulacaoConsorcio/DetalheSimulacao.cshtml", melhoresPropostas);
        }

        public ActionResult Detalhe(Guid id)
        {
            List<RetornoSimulacaoConsorcio> Simulacao = new List<RetornoSimulacaoConsorcio>();
            Parcelas parcelas = new Parcelas();
            List<Parcelas> parcelasAntes = new List<Parcelas>();
            List<Parcelas> parcelasApos = new List<Parcelas>();
            //TODO: Preencher as propriedades
            parcelas.ParcelaDe = 1;
            parcelas.ParcelaAte = 20;
            parcelas.ValorParcela = 120000;

            parcelasAntes.Add(parcelas);
            parcelasApos.Add(parcelas);

            RetornoSimulacaoConsorcio RetSimCons = new RetornoSimulacaoConsorcio
            (20000000, 25000000, 1500000, 1800, 18, parcelasAntes, parcelasApos, 15.5, 3.2, DateTime.Now, 20, 60);

            var financiamento = new Financiamento(5000000000, 3000000, 35000000, 8000000, 1300000, 200000, 50, 12);

            Simulacao.Add(RetSimCons);

            var detalheSimulacao = new DetalheSimulacao(Simulacao, financiamento);

            return View("~/Views/SimulacaoConsorcio/DetalheSimulacao.cshtml", detalheSimulacao);
        }

    }
}

GestaoConsorcio/Views/SimulacaoConsorcio/BuscarSimulacao.cshtml
@model List<GestaoConsorcio.Models.View.SimulacaoConsorcio>

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <a href="@Url.Action("NovaSimulacao", "SimulacaoConsorcio")" style=" float: right;
                                                                                    color: white;
                                                                                    font-size: 13px;
                                                                                    background: #0aa70a;
                                                                                    border: none;
                                                                                    border-radius: 5px;"
                   class="btn btn-sm">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true">Novo</span>
                </a>
                <div class="col-md-12">
                    <h3 class="page-header">
                        Lista de Simulações
                    </h3>
                    <div class="col-md-2">
                        <label>Nome do Cliente: </label>
                        <input type="text" class="form-control nomeCliente">
                    </div>
                    <div class="col-md-2">
                        <label>Valor da Carta: </label>
                        <input type="text" class="form-control valorCarta money">
                    </div>
                    <div class="col-md-2 ">
                        <div style="margin-top:29px;">
                            <button type="button" class="btn btn-sm btn-success btnbuscarAgendamentoHistorico" id="btnbuscarSimulacao">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span><strong> Buscar</strong>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12" id="formdetalhe">
                    <div class="table-responsive tablegeral">
                        <div class="table-responsive">
                            <table class="table table-hover ">
                                <thead>
                                    <tr>
                                        <th>Cliente</th>
                                        <th>Valor da Carta</th>
                                        <th>Parcela</th>
                                        @*<th>Contemplação</th>*@
                                        <th>Lance Próprio</th>
                                        <th>Info.</th>
                                    </tr>
                                </thead>
                                <tbody class="tbodygeral"></tbody>
                            </table>
                            <div id="pagethoje" align="center"></div>
                        </div>
                    </div>
                    <div id="pagetgeral" align="center" data-quantidade="">
                    </div>
                </div>
            </div>
        </div>
        <!-- /.container-fluid -->
    </div>

}

@section Js
{
    <script>
        $(document).ready(function () {
            Mascarar()
        });

        function Mascarar() {
            $('.money').mask('000.000.000.000.000,00', { reverse: true });
        }

        $('#btnbuscarSimulacao').click(function () {
            if (($('.nomeCliente').val() === undefined || $('.nomeCliente').val() === '')
                && ($('.valorCarta').val() === undefined || $('.valorCarta').val() === ''))
            {
                return alert('Favor preencher algum campo.');
            }
            var data = {
                nome: $('.nomeCliente').val(),
                valor: $('.valorCarta').val().split('.').join('').split(',').join('')
            }

            console.log(JSON.stringify(data));
            $.ajax({
                type: 'Post',
                contentType: 'application/json; charset=utf-8',
                url: '/SimulacaoConsorcio/BuscarSimulacao',
                data: JSON.stringify(data),
                success: function (json) {
                    $('.tbodygeral > tr').remove();
                    $(json).each(function () {
                        var info = $("<td><a href='SimulacaoConsorcio/Detalhe/" + this.IdSimulacao + "'><span class='glyphicon glyphicon-info-sign'></span></a></td>")
                        $('.tbodygeral')
                            .append('<tr> </tr>');
                        $('.tbodygeral tr:last ')
                            .append('<td>' + this.Nome + '</td>')
                            .append($("<td class='money'>" + this.ValorCarta + "</td>"))
                            .append('<td>' + this.Parcela + '</td>')
                            //.append('<td>' + this.Contemplacao + '</td>')
                            .append($("<td class='money'>" + this.LanceProprio + "</td>"))
                            .append(info);
                    });
                    //$("#divLoader").hide();
                    $("#btnbuscarAgendamentoHistorico").prop("disabled", false);
                    Mascarar();
                    if ($(json).length <= 0)
                        alert('Nenhum resultado encontrado.')
                },
                error: function () {
                    alert('error');
                    $("#divLoader").hide();
                    $("#btnbuscarAgendamentoHistorico").prop("disabled", false);
                }
            });
        });
    </script>
}

GestaoConsorcio/Views/SimulacaoConsorcio/DetalheSimulacao.cshtml
@model List<AnalisadorPerfilConsorcio.BuscarMelhoresPropostasResult>

@section Css{
    <link href="~/Scripts/plugins/LightweightFoldingMenu/jquery.treemenu.min.css" rel="stylesheet" />
}

@Html.AntiForgeryToken()
<div id="page-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @{ int i = 1; }

                <div class="col-md-3">
                    <ul class="tree">
                        <li>
                            <a href="#" class="lista">Lista</a>
                            <ul>
                                @foreach (var proposta in Model)
                                {
                                    <li>
                                        <a href="#" class="grupo @i">Grupo @i</a>
                                        <ul>
                                            @foreach (var cartas in proposta.ListaCartas)
                                            {
                                                <li><a href="#" class="carta @cartas.Carta.Id @i">Carta: @cartas.Carta.Id</a></li>
                                            }
                                        </ul>
                                    </li>
                                    i++;
                                }
                            </ul>
                        </li>
                    </ul>
                </div>

                <div class="lista col-sm-9" hidden>
                    <div>
                        <h3>Valores Informados</h3>
                        <div class="col-md-2">
                            <label>Vr do Bem: </label>
                            <input value="R$ @ViewBag.ParametrosValorCarta" name="Nome" type="text" class="form-control money" readonly>
                        </div>
                        <div class="col-md-2">
                            <label>Vr Parcela: </label>
                            <input value="R$ @ViewBag.ParametrosParcela" name="Nome" type="text" class="form-control money" readonly>
                        </div>
                        <div class="col-md-2">
                            <label>Recurso Próprio: </label>
                            <input value="R$ @ViewBag.ParametrosLance" name="Nome" type="text" class="form-control money" readonly>
                        </div>
                    </div>
                </div>

                @{ int aux = 1; }

                @foreach (var proposta in Model)
                {
                    <div class="col-sm-9 col-grupo pull-right grupo @aux" hidden>
                        @{
                            var valorProposta = Convert.ToInt64(proposta.Valor).ToString() + "00";
                            var valorParcela = Convert.ToInt64(proposta.Parcela).ToString() + "00";
                            var valorLance = Convert.ToInt64(proposta.Lance).ToString() + "00";
                        }
                        <h3>Grupo @aux</h3>
                        <div class="col-md-2">
                            <label>Total Bem: </label>
                            <input value="@int.Parse(valorProposta)" name="Nome" type="text" class="form-control money" readonly>
                        </div>

                        <div class="col-md-2">
                            <label>Total Parcela: </label>
                            <input value="@int.Parse(valorParcela)" name="Nome" type="text" class="form-control money" readonly>
                        </div>

                        <div class="col-md-3">
                            <label>Recurso Próprio: </label>
                            <input value="@valorLance" name="Nome" type="text" class="form-control money" readonly>
                        </div>

                    </div>

                            foreach (var carta in proposta.ListaCartas)
                            {
                                var lanceMedio = Convert.ToInt64(carta.Carta.LanceMedio).ToString() + "0000";
                                var valorparcela = Convert.ToInt64(carta.Carta.VrParcela).ToString() + "00";

                        <div class="carta col-sm-9 col-carta @carta.Carta.Id @aux pull-right" hidden>
                            <h3>Carta @carta.Carta.Id</h3>
                            <div class="col-md-2">
                                <label>Vr Bem: </label>
                                <input value="@carta.Carta.Valor" name="Nome" type="text" class="form-control money" readonly>
                            </div>
                            <div class="col-md-2">
                                <label>Vr Parcela: </label>
                                <input value="@valorparcela" name="Nome" type="text" class="form-control money" readonly>
                            </div>
                            <div class="col-md-3">
                                <label>Recurso Próprio: </label>
                                <input value="@carta.Carta.LanceProprioValor.ToString().Substring(0, carta.Carta.LanceProprioValor.ToString().Length - 6)" name="Nome" type="text" class="form-control money" readonly>
                            </div>
                            <div class="col-md-2">
                                <label>Qtde: </label>
                                <input value="@carta.Qtde" name="Nome" type="text" class="form-control money" readonly>
                            </div>
                        </div>
                    }
                    aux++;
                }
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</div>


@section Js
{
    <script src="~/Scripts/plugins/LightweightFoldingMenu/jquery.treemenu.min.js"></script>
    <script>

        $(document).ready(function () {
            $('.money').mask('000.000.000.000.000,00', { reverse: true });
        });

        $('a.lista').click(function () {
            $('.lista.col-sm-9').toggle();
        });

        $('a.carta').click(function () {
            var classe = $(this).removeClass('carta').attr('class').replace(' ', '.');
            console.log(classe);
            $('.col-sm-9.col-carta.' + classe).toggle();
        });

        $('a.grupo').click(function () {
            var classe = $(this).removeClass('grupo').attr('class').replace(' ', '.');
            console.log(classe);
            $('.col-sm-9.col-grupo.' + classe).toggle();
        });

        $(".tree").treemenu({ delay: 500 }).openActive();

    </script>
}

GestaoConsorcio/Views/SimulacaoConsorcio/NovaSimulacao.cshtml
@section Css{
    <link href="~/Scripts/plugins/Loaderjmspinner/jm.spinner.css" rel="stylesheet" />
}


@Html.AntiForgeryToken()
<div id="page-wrapper">
    <div class="container-fluid">
        <form action="@Url.Action("SimularConsorcio","SimulacaoConsorcio")" method="post">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-header">
                        Simulação (Lance Embutido)
                    </h3>
                    @*<div class="col-md-3">
                            <label>Nome do Cliente: </label>
                            <input name="Nome" type="text" class="form-control nomeCliente">
                        </div>*@
                    <div class="col-md-2">
                        <label>Valor da Carta: </label>
                        <input name="ValorCarta" type="text" class="form-control valorCarta money">
                    </div>
                    @*<div class="col-md-2">
                            <label>Renda: </label>
                            <input name="Renda" type="text" class="form-control renda money">
                        </div>*@
                    <div class="col-md-2">
                        <label>Parcelas: </label>
                        <input name="Parcela" type="text" class="form-control parcela money">
                    </div>
                    <div class="col-md-2">
                        <label>Recurso Próprio: </label>
                        <input name="Lance" type="text" class="form-control lance money">
                    </div>
                    <div class="col-md-3">
                        <input name="IncluirGrupoFormacao" type="checkbox" value="false">
                        <label>Incluir Grupo Formacao? </label>
                    </div>
                    @*<div class="col-md-2">
                            <label>Número Máx. Cartas: </label>
                            <input name="NumeroMaxCartas" type="text" class="form-control maxCartas">
                        </div>*@
                    @*<div class="col-md-2">
                            <label>Expec. Contemplação: </label>
                            <input type="text" class="form-control contemplacao">
                        </div>*@
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                </div>
            </div>

            <div class="row">
                @*<div class="col-md-12">
                        <h3>O que deseja?</h3>
                    </div>
                    <div class="col-md-2">
                        <input name="MenorParcela" type="checkbox" id="menorParcela" />
                        <label for="menorParcela">Menor Parcela</label>
                    </div>
                    <div class="col-md-2">
                        <input name="MenorLance" type="checkbox" id="menorParcela" />
                        <label for="menorLance">Menor Lance</label>
                    </div>*@
                @*<div class="col-md-3">
                        <input type="checkbox" id="menorParcela" />
                        <label for="menorTempo">Menor Tempo para Contemplação</label>
                    </div>*@
                <div class="col-md-2">
                    <input type="submit"
                           class="btn btn-sm btnSimular"
                           style="text-decoration: none !important;
                            margin-left: 15px;
                            color: white;
                            background: #0aa70a;
                            border: none;
                            border-radius: 5px;"
                           value="Simular">
                </div>
            </div>
        </form>

    </div>
    <!-- /.container-fluid -->
</div>


@section Js
{
    <script src="~/Scripts/plugins/Loaderjmspinner/jm.spinner.js"></script>

    <script>
        $(document).ready(function () {
            $('.money').mask('000.000.000.000.000,00', { reverse: true });
        });

        $("input[type=checkbox]").change(function () {
            if ($(this).prop("checked")) {
                $(this).val(true);
            } else {
                $(this).val(false);
            }
        });

        $('.btnSimular').click(function () {
            $('form').submit();
            $('#page-wrapper').jmspinner();
        });
    </script>
}