GestaoConsorcio/Models/Banco/Campanha.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoConsorcio.Models.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campanha
    {
        public Campanha()
        {
            this.ContatoCampanhas = new HashSet<ContatoCampanha>();
        }
    
        public int CampanhaID { get; set; }
        public string Nome { get; set; }
        public System.DateTime CriadoEm { get; set; }
    
        public virtual ICollection<ContatoCampanha> ContatoCampanhas { get; set; }
    }
}

GestaoConsorcio/Controllers/CampanhasController.cs
using GestaoConsorcio.Models.Banco;
using GestaoConsorcio.Models.Repositorio;
using GestaoConsorcio.Models.Util;
using GestaoConsorcio.Models.View;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestaoConsorcio.Controllers
{
    [Authorize]
    public class CampanhasController : Controller
    {
        private CampanhasBD bdcamp = new CampanhasBD();

        public ActionResult Index()
        {
            int qtde = 0;

            if (User.IsInRole("Administrador") || User.IsInRole("BackOfficeDoc") || User.IsInRole("BackOfficeLig") || User.IsInRole("Caixa"))
            {
                qtde = bdcamp.ContarCampanhas();
            }
            else
            {
                qtde = bdcamp.ContarCampanhas(usuid: int.Parse(User.Identity.GetUserId()));
            }

            ViewBag.Count = qtde;
            ViewBag.Usuario = User.Identity.GetUserId();

            return View();
        }

        [Route("exportar-consultores")]
        [HttpGet]
        public ActionResult ExportarRelatorio(string nomeOuEmail = "", string grupo = "",
            string dataInicio = null, string dataFim = null, string campoData = "lead", string ordenacao = "desc", int registros = 20, bool somentePresidentes = false, int presidente = 0)
        {
            List<ContatoCampanha> ret = null;

            if (User.IsInRole("Administrador") || User.IsInRole("BackOfficeDoc") || User.IsInRole("BackOfficeLig") || User.IsInRole("Caixa"))
            {
                ret = bdcamp.BuscarContatosCampanhas(0);
            }
            else
            {
                ret = bdcamp.BuscarContatosCampanhas(int.Parse(User.Identity.GetUserId()));
            }

            var relatorio = ret.Select(x => new {
               Nome = x.Nome,
               Telefone = x.Telefone,
               Email = x.Email,
               UF = x.Estado,
               Data = x.CriadoEm.ToString("dd/MM/yyy HH:mm:ss"),
               UltimaAcao = x.ObservacaoContatoes.Count() > 0 ? ((DateTime)x.ObservacaoContatoes.Max(o => o.CriadoEm)).ToString("dd/MM/yyy HH:mm:ss") : null,
               ValorDaCarta = x.ValoresCarta,
               Renda = x.Renda,
               MelhorHorario = x.MelhorHorario,
               Status = x.UltimaAcaoDesc,
               PropostaEnviada = x.CCampTags.Any(o=>o.TagContatoFK == 8)?"Sim":"Não",
               Finalizado = x.CCampTags.Any(o => o.TagContatoFK == 6) ? "Sim" : "Não",
            }).ToList();

            var nomeArquivo = "RelatorioConsultores" + DateTime.Now.ToString("dd/MM/yyy HH:mm:ss") + ".xlsx";
            var fileContent = EppExcelExport.ExportExcel(relatorio);
            return File(fileContent, EppExcelExport.ExcelContentType, nomeArquivo);
        }

        public ActionResult Detalhe(int contatoid)
        {
            var Model = bdcamp.BuscarContatoPorID(contatoid);
            var obss = bdcamp.ListarObservacoes(contatoid);

            ViewBag.Lista = obss.Select(x => new ObsCCampVM() {
                                Id = x.ObservacaoContatoID,
                                Consultor = x.Usuario == null ? "" : x.Usuario.Nome,
                                Texto = x.Texto,
                                Data = x.CriadoEm
                            }).ToList();

            ViewBag.Invalido = bdcamp.VerificarTagContato(contatoid, 2)? "checked":"";
            ViewBag.CxPostal = bdcamp.VerificarTagContato(contatoid, 7) ? "checked" : "";
            ViewBag.Incompativel = bdcamp.VerificarTagContato(contatoid, 11) ? "checked" : "";
            ViewBag.Pesquisando = bdcamp.VerificarTagContato(contatoid, 9) ? "checked" : "";
            ViewBag.Enviada = bdcamp.VerificarTagContato(contatoid, 8) ? "checked" : "";
            ViewBag.Finalizado = bdcamp.VerificarTagContato(contatoid, 6) ? "checked" : "";
            ViewBag.Desconto = bdcamp.VerificarTagContato(contatoid, 10) ? "checked" : "";
            

            ViewBag.ListaConsultores = new SelectList(
                                            new ComboBD().ComboConsultorBD(),
                                            "consultorid",
                                            "nome"
                                        );

            return View(Model);
        }

        [HttpPost]
        public ActionResult Gravar(ContatoCampanha dados)
        {
            bdcamp.Salvar(dados);

            return RedirectToAction("Index");
        }

        private DateTime? String2Date(string texto)
        {
            try
            {
                if (string.IsNullOrEmpty(texto)) return null;

                var list = texto?.Split('-');
                if (list.Count() > 2)
                {
                    return new DateTime(Int32.Parse(list[0]), Int32.Parse(list[1]), Int32.Parse(list[2]));
                }
                else
                {
                    return null;
                }
            }
            catch
            {
                return null;
            }

        }

        public JsonResult BuscarCampanha(int pag = 0, int usuid = 0, int campanhafk = 0, string inicio = null, string fim = null)
        {
            if (usuid == 0)
            {
                usuid = Int32.Parse(User.Identity.GetUserId());
            }
            
            var busca = bdcamp.BuscarContatosCampanhas(pag, usuid, campanhafk, String2Date(inicio), String2Date(fim));

            var lista = busca.Select(x => new
            {
                ContatoCampanhaID = x.ContatoCampanhaID,
                UltimaAcao = x.ObservacaoContatoes.Count() > 0 ? x.ObservacaoContatoes.Max(o => o.CriadoEm.ToString("dd/MM/yyy HH:mm:ss")) : " - ",
                Estado = x.Estado ?? " - ",
                CriadoEm = x.CriadoEm.ToString("dd/MM/yyy HH:mm:ss"),
                Nome = x.Nome ?? " - ",
                Telefone = x.Telefone ?? " - ",
                ValoresCarta = x.ValoresCarta ?? " - ",
                UltimaAcaoDesc = x.UltimaAcaoDesc ?? " - "
            }).ToList();


            return Json(lista);

        }

        [HttpGet]
        public ActionResult Importacao()
        {
            return View(new CampanhaImportacaoVM());
        }


        [HttpPost]
        public ActionResult Importacao(CampanhaImportacaoVM model)
        {
            if (model.CampanhaID == 0 || model.ComboConsultorID == 0)
            {
                return View(model);
            }

            DataTable tab = GetTable(model.Texto);

            bdcamp.SalvarImportacao(tab, model.ComboConsultorID, model.CampanhaID);

            return RedirectToAction("Index");
        }

        private DataTable GetTable(string texto)
        {
            bool first = true;
            string[] linhas = texto.Replace("\r", "").Split('\n');
            DataTable table = new DataTable();

            foreach (string linha in linhas)
            {
                string[] colunas = linha.Split(';');
                if (first)
                {
                    foreach (string nomecol in colunas)
                    {
                        table.Columns.Add(nomecol, typeof(string));
                    }
                    first = false;
                }
                else
                {
                    table.Rows.Add(colunas);
                }
            }

            return table;
        }


        [HttpPost]
        public ActionResult SalvarObs(string txt, int contatoid, DateTime? data)
        {
            bdcamp.SalvarObs(int.Parse(User.Identity.GetUserId()), contatoid, txt, data??DateTime.Now);

            return null;
        }

        public ActionResult SalvarTagContato(int contatoid, int tagid, bool status)
        {
            if (status)
            {
                bdcamp.AssociarTagContato(contatoid, tagid);
            }
            else
            {
                bdcamp.ApagarTagContato(contatoid, tagid);
            }

            return null;
        }

        public ActionResult SalvarTagObs(int obsid, int tagid, int status)
        {
            //bdcamp.SalvarObs(int.Parse(User.Identity.GetUserId()), contatoid, txt);

            return null;
        }

    }
}

GestaoConsorcio/Views/Campanhas/Detalhe.cshtml
@model GestaoConsorcio.Models.Banco.ContatoCampanha 

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var lista = ViewBag.Lista;

}



@using (Html.BeginForm("Gravar", "Campanhas", FormMethod.Post, new { Id = "Form1" }))
{
    @Html.AntiForgeryToken()
    <div id="page-wrapper">
        <div class="container-fluid">
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="page-header">
                        @Model.Nome
                    </h3>

            @if (User.IsInRole("Administrador") || User.IsInRole("BackOfficeDoc") || User.IsInRole("BackOfficeLig"))
            {
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Responsável</label>
                                @Html.DropDownListFor(x => x.UsuarioFK, (SelectList)ViewBag.ListaConsultores, "Nenhum", new { @class = "form-control" })
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>
            }
            else
            {
                @Html.HiddenFor(x => x.UsuarioFK)
            }


                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Telefone</label>
                                <input type="text" class="form-control novonome" name="Telefone" id="Telefone" value="@Html.DisplayFor(x=> x.Telefone)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="text" class="form-control novonome" name="Email" id="Email" value="@Html.DisplayFor(x=> x.Email)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Estado</label>
                                <input type="text" class="form-control novonome" name="Estado" id="Estado" value="@Html.DisplayFor(x=> x.Estado)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Data Caixa</label>
                                <input type="text" class="form-control novonome" name="FeitoEm" id="FeitoEm" value="@Html.DisplayFor(x=> x.FeitoEm)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Renda</label>
                                <input type="text" class="form-control novonome" name="Renda" id="Renda" value="@Html.DisplayFor(x=> x.Renda)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Carta</label>
                                <input type="text" class="form-control novonome" name="ValoresCarta" id="ValoresCarta" value="@Html.DisplayFor(x=> x.ValoresCarta)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Parcela</label>
                                <input type="text" class="form-control novonome" name="ValoresParcela" id="ValoresParcela" value="@Html.DisplayFor(x=> x.ValoresParcela)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Melhor Horario</label>
                                <input type="text" class="form-control novonome" name="MelhorHorario" id="MelhorHorario" value="@Html.DisplayFor(x=> x.MelhorHorario)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagInvalido" id="TagInvalido" onclick="SalvarChk(2, '#TagInvalido', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.Invalido />
                                <label>Inválido</label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagCxPostal" id="TagCxPostal" onclick="SalvarChk(7, '#TagCxPostal', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.CxPostal />
                                <label>Cx postal/não atende</label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagCompativel" id="TagCompativel" onclick="SalvarChk(11, '#TagCompativel', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.Incompativel />
                                <label>Renda não compatível</label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagPesquisando" id="TagPesquisando" onclick="SalvarChk(9, '#TagPesquisando', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.Pesquisando />
                                <label>Pesquisando</label>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagEnviada" id="TagEnviada" onclick="SalvarChk(8, '#TagEnviada', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.Enviada />
                                <label>Proposta enviada</label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagFinalizado" id="TagFinalizado" onclick="SalvarChk(6, '#TagFinalizado', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.Finalizado />
                                <label>Finalizado</label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input type="checkbox" name="TagDesconto" id="TagDesconto" onclick="SalvarChk(10, '#TagDesconto', @Html.DisplayFor(x=>x.ContatoCampanhaID))" @ViewBag.Desconto />
                                <label>Desconto (medico, advogado)</label>
                            </div>
                        </div>
                    </div>
                 

                    <div class="row">
                        <div class="col-md-6">
                        @if (!User.IsInRole("Caixa")) {
                            <button type="submit" class="btn btn-success">
                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span><strong> Salvar Alterações do Cadastro</strong>
                            </button>
                        }
                            <button type="button" class="btn btn-warning" onclick="voltar()">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span><strong> Voltar Para a Lista</strong>
                            </button>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="hidden" class="form-control novonome" name="ContatoCampanhaID" id="ContatoCampanhaID" value="@Html.DisplayFor(x=> x.ContatoCampanhaID)">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col-md-9">
                            <div class="form-group">
                                <label>Observacao</label>
                                <input type="text" class="form-control"  name="Observacao" id="Observacao" value="">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label>Data</label>
                                <input type="text" class="form-control"  name="DataObs" id="DataObs" value="@DateTime.Now">
                                <span class="glyphicon form-control-feedback" id="nomecliente1"></span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <button type="button" class="btn btn-success" onclick="SalvarObservacao()">
                                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span><strong> Salvar Observacao</strong>
                                </button>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12" id="formdetalhe">
                            <div class="table-responsive tablegeral">
                                <div class="table-responsive">
                                    <table class="table table-hover ">
                                        <thead>
                                            <tr>
                                                <th>Data</th>
                                                <th>Texto</th>
                                                <th>Consultor</th>
                                            </tr>
                                        </thead>
                                        <tbody class="tbodygeral">
                                            @if (lista != null)
                                            {
                                                var aux = lista.Count - 1;

                                                for (int i = 0; i <= aux; i++)
                                                {
                                                    <tr>
                                                        <td>@lista[i].Data</td>
                                                        <td>@lista[i].Texto</td>
                                                        <td>@lista[i].Consultor</td>
                                                    </tr>
                                                }
                                            }

                                        </tbody>

                                    </table>
                                    <div id="pagethoje" align="center"></div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


    

}

<script>

    function voltar() {
        window.history.back();
    }

    function SalvarObservacao() {

        $.ajax({
            type: 'POST',
            url: '/Campanhas/SalvarObs',
            data: 'txt=' + $("#Observacao").val() + '&contatoid=' + $("#ContatoCampanhaID").val() + '&data=' + $("#DataObs").val(),
            success: function (msg) {
                window.location.reload(true);
            }
        });

    }

    function SalvarChk(id, loc, contatoid) {
        var chk = $(loc).is(":checked");
        $.ajax({
            type: 'POST',
            url: '/Campanhas/SalvarTagContato',
            data: 'contatoid=' + contatoid + '&tagid=' + id + '&status=' + chk,
        });

    }
</script>

GestaoConsorcio/Views/Campanhas/Importacao.cshtml
@model GestaoConsorcio.Models.View.CampanhaImportacaoVM
@{
    ViewBag.Title = "Importacao";
    Layout = "~/Views/Shared/_LayoutCampanha.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div id="page-wrapper">
        <div class="container-fluid">

            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-header">
                        Campanhas - Importação
                    </h3>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <label>Use os seguintes campos</label>
                    Nome, Telefone, Email, Estado, Renda, FeitoEm (data do lead), ValoresCarta, ValoresParcela, Sexo, MelhorHorario, OrigemTxt, Texto1, Texto2, Obs1, Obs2, Obs3, Obs4
                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label>Campanha: </label>
                    <select id="CampanhaID" name="CampanhaID" class="form-control">
                        <option value="0">Selecione</option>
                        <option value="1">Antiga</option>
                        <option value="2">Feirão</option>
                        <option value="3">Indicação</option>
                    </select>
                </div>
                <div class="col-md-2">

                    <label>Consultor: </label>
                    <select id="ComboConsultorID" name="ComboConsultorID" class="form-control">
                        <option>Selecione</option>
                    </select>

                </div>
            </div>

            <div class="row">
                <div class="col-md-2">
                    <label>Texto: </label>
                    @Html.TextAreaFor(x => x.Texto, new { style = "width:600px;height:400px" })
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 ">
                    <button type="submit" class="btn btn-sm btn-success btnimportacao">
                        <span class="glyphicon" aria-hidden="true"></span><strong>Importar</strong>
                    </button>

                </div>
            </div>

        </div>
        <!-- /.container-fluid -->
    </div>


}


<script>

    $(document).ready(function () {

        $.ajax({
            type: 'post',
            contentType: 'application/json; charset=utf-8',
            url: '/Combo/ComboConsultor',
            success: function (json) {
                var a = "";

                $(json).each(function () {

                    a += "<option value=" + this.consultorid + ">" + this.nome + " " + this.sobrenome + "</option>";

                });

                $("#ComboConsultorID").append(a);
            }

        });

    });
</script>